CREATE TABLE EXTBDC1 (
    BUN NUMERIC(8),  
    PID NUMERIC(10),  
    DOC_NO CHAR(30),  
    DOC_SEQ NUMERIC(2),  
    DOC_CNT NUMERIC(2),  
    DOC_KIND NUMERIC(1),  
    ACTIVE_FLG NUMERIC(1),  
    DOC_DATAX NVARCHAR(max)
);  
