CREATE TABLE ECSCSM_ECTBSM ( 
  PID NUMERIC(10),
  SUM_SYUBETU CHAR(2),
  SUM_SEQ NUMERIC(2),
  NOW_DATE NUMERIC(14),
  NOW_KA CHAR(3),
  NOW_DOC_K CHAR(4),
  ORIGINAL_DATE NUMERIC(14),
  ORIGINAL_KA CHAR(3),
  ORIGINAL_DOC_K CHAR(4),
  TAIIN_DATE NUMERIC(14),
  TAIIN_DOC_K CHAR(4),
  CR_STATE CHAR(2),
  CR_DATE NUMERIC(14, 0),
  CHK_STATE CHAR(2),
  UKE_STATE CHAR(2)
);
